---
apiVersion: "v1"
kind: "List"
items:
  - apiVersion: "v1"
    kind: "Service"
    metadata:
      name: "kubernetes-java-annotations"
    spec:
      ports:
        - name: "srv"
          port: 8080
          targetPort: 8080
      selector:
        app: "kubernetes-java-annotations"
        version: "0.0.1-SNAPSHOT"
        group: "alexandru.lungu"
      type: "LoadBalancer"
  - apiVersion: "apps/v1"
    kind: "Deployment"
    metadata:
      name: "kubernetes-java-annotations"
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: "kubernetes-java-annotations"
          version: "0.0.1-SNAPSHOT"
          group: "alexandru.lungu"
      template:
        metadata:
          labels:
            app: "kubernetes-java-annotations"
            version: "0.0.1-SNAPSHOT"
            group: "alexandru.lungu"
        spec:
          containers:
            - env:
                - name: "KUBERNETES_NAMESPACE"
                  valueFrom:
                    fieldRef:
                      fieldPath: "metadata.namespace"
                - name: "key1"
                  value: "value1"
                - name: "SPRING_BOOT_APP_ENV_CONFIG_APP_DESC"
                  valueFrom:
                    configMapKeyRef:
                      # The ConfigMap containing the value you want to assign to SPRING_BOOT_APP_ENV_CONFIG_APP_DESC
                      name: app-config-map
                      # Specify the key associated with the value
                      key: appName
              image: "alexandru.lungu/kubernetes-java-annotations:0.0.1-SNAPSHOT"
              imagePullPolicy: "IfNotPresent"
              name: "kubernetes-java-annotations"
              ports:
                - containerPort: 8080
                  hostPort: 8080
                  name: "srv"
                  protocol: "TCP"
